Iter13
smakimka/mtrcscollector pull request #17
Opened 2024-01-21 14:52 UTC by smakimka

2024-01-22 16:53 UTC, rktkov requested changes

2024-01-22 16:53 UTC, rktkov commented on internal/storage/pgstorage.go
> +func (s PGStorage) CreateSchemaIFNotExists(ctx context.Context) error {
CreateSchemaIfNotExists

2024-01-22 16:53 UTC, rktkov commented on internal/storage/pgstorage.go
> +	row := s.p.QueryRow(ctx, "select id, value from counter_metrics where name like $1", m.Name)
Стоит все запросы сделать в контексте одной транзакции, потому что между любым из них может уже исполняться параллельный запрос от другого клиентского взаимодействия.
Ниже ведь используется такой подход.

2024-01-22 16:53 UTC, rktkov commented on internal/storage/pgstorage.go
> +func (s PGStorage) UpdateGaugeMetric(ctx context.Context, m model.GaugeMetric) error {
см. комментарий выше

2024-01-22 16:53 UTC, rktkov commented on internal/storage/pgstorage.go
> +	for _, metricData := range metricsData {
Стоит подумать как выполнить все изменения за один запрос по каждому из типов метрик.

2024-01-22 16:53 UTC, rktkov commented on cmd/server/main.go
> +	"github.com/jackc/pgx/v5/pgxpool"
Не хватает разделения блоков.

2024-01-24 11:58 UTC, smakimka commented on internal/storage/pgstorage.go
> +	for _, metricData := range metricsData {
Если я правильно понял, то сделал, если нет, то, возможно, я неправильно понял само задание - я думаю что в этом запросе могут быть метрики, которых раньше не было, т.е. просто update не подходит. Надо как-то это учитывать, и это либо несколько запросов на метрику, либо upsert, который я сделал, объединить upsert-ы в один запрос тоже вроде не получается, т.к. невозможно указать в update части разыне значения.

2024-01-26 11:18 UTC, rktkov approved these changes

2024-01-30 12:11 UTC, merged