Iter25
smakimka/mtrcscollector pull request #28
Opened 2024-05-31 23:27 UTC by smakimka

2024-06-01 22:44 UTC, Bazys commented on internal/agent/config/config.go
>  type JsonConfig struct {
```suggestion
type JSONConfig struct {
```

2024-06-01 22:45 UTC, Bazys commented on internal/agent/config/config.go
> +		} else {
```suggestion
		} else if {
```

2024-06-01 22:50 UTC, Bazys commented on internal/server/config/config.go
>  func parseFlags() *Config {
супер божественная функция!
не влезает в 2 экрана - значит надо разбивать

2024-06-01 22:51 UTC, Bazys requested changes
1. context.Context всегда первым аргументом в сигнатуре функции
2. s.UpdateGaugeMetric - возвращает ошибку, а ты ни разу ее не проверяешь
3. Очень много неиспользуемых параметров в сигнатуре функции, заменяй на _

2024-06-17 09:04 UTC, smakimka commented on internal/server/config/config.go
>  func parseFlags() *Config {
В этой функции инициализируется конфиг, это действие можно разбить, наверное, сделав функцию по каждому параметру, но это просто куча лишних функций, я думаю. Мне кажется, что то, что все  параметры собраны в одну функцию делает это более понятным, т.к. всё действие в одном месте, не надо никуда смотреть. Тем более что это достаточно понятно, т.к. там просто многократно повторяется одно и тоже действие. Она получается длинной из-за этого, но я не вижу в этом ничего плохого.
У меня влезает в 2 экрана)

2024-06-17 09:05 UTC, smakimka commented
1. Вроде везде поправил.
2. Ошибка возвращается из-за того что это интерфейс, который должны реализовывать и memory storage и pgstorage, т.к. операции с базой данных возвращают ошибку. В MemStorage, который всегда используется в агенте, это всегда nil.
3. Не понял о какой функции идет речь

2024-06-18 19:19 UTC, Bazys requested changes
на одинаковые вещи замечния не дублирую

2024-06-18 19:19 UTC, Bazys commented on internal/agent/send.go
>  func SendMetrics(ctx context.Context, cfg *config.Config, s storage.Storage, jobs chan<- model.MetricsData, errs chan<- error) {
Параметр функции, названный `cfg`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `cfg` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-06-18 19:19 UTC, Bazys commented on internal/agent/config/config.go
> +		} else if !cfg.GRPC {
тут `else if` а в коде выше почему сразу не исправил?

2024-06-19 19:58 UTC, Bazys approved these changes
Хорошо, продолжаем

2024-06-20 19:06 UTC, merged