Iter5
smakimka/mtrcscollector pull request #8
Opened 2023-12-06 18:25 UTC by smakimka

2023-12-08 20:44 UTC, rktkov requested changes

2023-12-08 20:44 UTC, rktkov commented on internal/storage/memstorage.go
> +func (s *MemStorage) Init() error {
В го структуры принято иницилизировать через функции пакета, которые называются New<StructName>.

2023-12-08 20:44 UTC, rktkov commented on internal/storage/memstorage.go
> +func (s *MemStorage) Init() error {
А еще функция возвращает еррор, которая всегда нул - это лишнее.

2023-12-08 20:44 UTC, rktkov commented on internal/storage/memstorage.go
> +	Mutex          sync.RWMutex
Не уверен, что стоит мютекс делать общедоступным полем. Лучше его сделать закрытым для структуры.

2023-12-08 20:44 UTC, rktkov commented on internal/storage/memstorage.go
> +	Mutex          sync.RWMutex
Тоже самое и про логгер, да и поля хранения. Короче все бы надо спрятать от внешнего мира.

2023-12-08 20:44 UTC, rktkov commented on internal/mtrcs/counter.go
> +package mtrcs
Я бы пакет назвал  model.

2023-12-08 20:44 UTC, rktkov commented on internal/mtrcs/metric.go
> +type Metric interface {
В ГО интерфейсы принято называть отглагольными существительными, например глагол Read ->  интерфейс Reader и т.д.

2023-12-08 20:44 UTC, rktkov commented on internal/mtrcs/metric.go
> +	GetValue() interface{}
Такой подход приведет к наличию везде по коду проверок на тип и последующие приведения к нужному. Желание сделать по классической схеме ООП понятно, не настаиваю на переписывании, но в принципе в го нормальная практика писать много повторяющегося кода, если он понятный и простой.

2023-12-08 20:44 UTC, rktkov commented on cmd/server/middleware/storage.go
> +func (s WithMemStorage) WithMemStorage(next http.Handler) http.Handler {
Вот этого не стоит делать - не надо проводить скрытые иньекции через контекст. Потому что так происходит связывание следующих слоев обработки с верхними, и они не смогут существовать без них. А еще это создает "скрытую" от других разработчиков зависимость от цепочки обработки запроса. Гораздо прозрачнее в обраобтчиках использовать экземпляр "внешнего слоя", который получается в момент инициализации слоя обработки.

2023-12-08 20:44 UTC, rktkov commented on cmd/server/router.go
> +	s := &storage.MemStorage{Logger: logger}
Вот меняем на NewStorage

2023-12-08 20:44 UTC, rktkov commented on cmd/server/router.go
> +		log.Fatal(err)
Не стоит злоупотреблять фаталами на нижних слоях приложения, лучше вернуть еррор и предоставить возможность клиентскому коды принять решения, как поступить в случае ошибки.

2023-12-08 20:44 UTC, rktkov commented on cmd/server/router.go
> +	"github.com/go-chi/chi/v5"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2023-12-08 20:44 UTC, rktkov commented on cmd/server/handlers/allmtrcs.go
> +package handlers
Лучше придерживаться консистентности в именовании файлов. Либо все имена файлов сокращаем, либо все пишем с использованием полных слов.

2023-12-08 20:44 UTC, rktkov commented on cmd/server/main.go
> +import (
Я бы все оставльные пакеты из этой папки перенес бы в internal. А тут оставил бы только main

2023-12-08 20:44 UTC, rktkov commented on cmd/server/flags.go
> +type Config struct {
Это больше похоже на config, а не flags.  И я бы сделал фукнцию NewConfig куда бы спрятал вызов парсинга флагов.

2023-12-08 20:44 UTC, rktkov commented on cmd/agent/main.go
> +func main() {
Те же рекомендации, что для сервера по конфигу и остальным файлам кроме main

2023-12-08 20:44 UTC, rktkov commented on cmd/agent/main.go
> +	wg.Add(1)
Тут тоже есть вопросы, но думаю код исправиться, когда в теории дойдет до соотвествующих тем. Так что можно так оставлять, пока.

2023-12-17 12:49 UTC, smakimka commented on internal/storage/memstorage.go
> +func (s *MemStorage) Init() error {
New сделал

Для NewMemStorage ошибка не возвращается.
В интерфейсе функции всё ещё возвращают ошибку потому что я предполагаю, что потом с бд это будет иметь смысл, т.к. там бывают ошибки соединения и т.д.

2023-12-17 12:50 UTC, smakimka commented on internal/storage/memstorage.go
> +	Mutex          sync.RWMutex
Теперь все поля приватные

2023-12-17 12:50 UTC, smakimka commented on internal/mtrcs/counter.go
> +package mtrcs
Переименовано

2023-12-17 12:51 UTC, smakimka commented on internal/mtrcs/metric.go
> +type Metric interface {
Интерфейса больше нет, см. след change, если это change называется

2023-12-17 12:52 UTC, smakimka commented on internal/mtrcs/metric.go
> +	GetValue() interface{}
Поменял на 2 структуры, GaugeMetric и CounterMetric, соответсвенно все методы интерфейса Storage теперь *2, но с разными типами

2023-12-17 12:55 UTC, smakimka commented on cmd/server/middleware/storage.go
> +func (s WithMemStorage) WithMemStorage(next http.Handler) http.Handler {
Убрал, теперь handler-ы это http.Handler-ы и у них есть поля для storage и logger, кажется, что context лучше, но пока 2 поля оставил

2023-12-17 12:57 UTC, smakimka commented on cmd/agent/main.go
> +	wg.Add(1)
Попробовал сделать получше (в пачке был паттерн как это делается в обсуждении)

2023-12-18 07:55 UTC, rktkov approved these changes

2023-12-20 22:31 UTC, merged